<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="c:\program files (x86)\microsoft visual studio\2017\community\team tools\static analysis tools\fxcop\Xml\CodeAnalysisReport.xsl"?>
<FxCopReport Version="15.0">
 <Targets>
  <Target Name="C:\Users\ISAACELEAZAR\AppData\Local\Temp\tmp466D.tmp.cadir\bin\App_Code.dll">
   <Modules>
    <Module Name="app_code.dll">
     <Namespaces>
      <Namespace Name="">
       <Types>
        <Type Name="Correo" Kind="Class" Accessibility="Public" ExternallyVisible="True">
         <Members>
          <Member Name="#enviarCorreo(System.String,System.String,System.String)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="No usar Dispose varias veces en objetos" Category="Microsoft.Usage" CheckId="CA2202" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="DependsOnFix">
             <Issue Certainty="75" Level="Warning" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code" File="Correo.cs" Line="26">El objeto 'Emailtemplate' admite Dispose más de una vez en el método 'Correo.enviarCorreo(string, string, string)'. Para evitar generar una excepción System.ObjectDisposedException, no debe llamar a Dispose más de una vez en un objeto.: Lines: 26</Issue>
            </Message>
           </Messages>
          </Member>
         </Members>
        </Type>
        <Type Name="DAOUsuario" Kind="Class" Accessibility="Public" ExternallyVisible="True">
         <Members>
          <Member Name="#actualizarPedido(System.Boolean,System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="959">'DAOUsuario.actualizarPedido(bool, int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#actualziarContrasena(EUsuario)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="98">'DAOUsuario.actualziarContrasena(EUsuario)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#almacenarToken(System.String,System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="211">'DAOUsuario.almacenarToken(string, int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#cerrarSession(EUsuario)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="126">'DAOUsuario.cerrarSession(EUsuario)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#crearAsignacion(Asignacion)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="604">'DAOUsuario.crearAsignacion(Asignacion)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#crearAsignaciones(Asignacion,System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="573">'DAOUsuario.crearAsignaciones(Asignacion, int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#crearPedido(Pedido)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="752">'DAOUsuario.crearPedido(Pedido)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#crearPedidos(Asignacion,System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="900">'DAOUsuario.crearPedidos(Asignacion, int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#crearProducto(Producto)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="424">'DAOUsuario.crearProducto(Producto)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#crearSede(Sede)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="270">'DAOUsuario.crearSede(Sede)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#editarCantidad(System.Int32,System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="720">'DAOUsuario.editarCantidad(int, int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#editarProducto(Producto)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="514">'DAOUsuario.editarProducto(Producto)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#eliminarAsignacion(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="660">'DAOUsuario.eliminarAsignacion(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#eliminarPedidos(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="808">'DAOUsuario.eliminarPedidos(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#eliminarProducto(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="541">'DAOUsuario.eliminarProducto(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#eliminarSede(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="392">'DAOUsuario.eliminarSede(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#generarToken(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="182">'DAOUsuario.generarToken(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#guardadoSession(EUsuario)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="69">'DAOUsuario.guardadoSession(EUsuario)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#loggin(System.String,System.String)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="38">'DAOUsuario.loggin(string, string)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#obtenerUsuarios(System.String)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="154">'DAOUsuario.obtenerUsuarios(string)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#obtenerUsusarioToken(System.String)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="239">'DAOUsuario.obtenerUsusarioToken(string)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#validarAsignacion(System.String,System.Double)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="688">'DAOUsuario.validarAsignacion(string, double)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verAsignaciones()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="631">'DAOUsuario.verAsignaciones()' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verPedido()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="779">'DAOUsuario.verPedido()' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verPedidos(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="928">'DAOUsuario.verPedidos(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verProductos()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="451">'DAOUsuario.verProductos()' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verProductosEditar(System.Int32)" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="480">'DAOUsuario.verProductosEditar(int)' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verSedes()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="297">'DAOUsuario.verSedes()' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verUltimoId()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="835">'DAOUsuario.verUltimoId()' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
          <Member Name="#verUltimoId2()" Kind="Method" Static="False" Accessibility="Public" ExternallyVisible="True">
           <Messages>
            <Message TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200" Status="Active" Created="2018-10-20 16:40:08Z" FixCategory="NonBreaking">
             <Issue Certainty="95" Level="Error" Path="C:\Users\ISAACELEAZAR\Desktop\2018-II\Ing de Software\SCA\App_Code\Datos" File="DAOUsuario.cs" Line="864">'DAOUsuario.verUltimoId2()' vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Issue>
            </Message>
           </Messages>
          </Member>
         </Members>
        </Type>
       </Types>
      </Namespace>
     </Namespaces>
    </Module>
   </Modules>
  </Target>
 </Targets>
 <Rules>
  <Rule TypeName="No usar Dispose varias veces en objetos" Category="Microsoft.Usage" CheckId="CA2202">
   <Name>No usar Dispose varias veces en objetos</Name>
   <Description>Un método Dispose correctamente implementado se puede llamar varias veces sin producir ninguna excepción. Sin embargo, esto no está garantizado y, para evitar generar una excepción System.ObjectDisposedException, no debe llamar al método Dispose más de una vez en un objeto.</Description>
   <Resolution Name="Default">El objeto {0} admite Dispose más de una vez en el método {1}. Para evitar generar una excepción System.ObjectDisposedException, no debe llamar a Dispose más de una vez en un objeto.: Lines: 26</Resolution>
   <Owner>RuleOwner</Owner>
   <Url>http://msdn.microsoft.com/library/ms182334.aspx</Url>
   <Email />
   <MessageLevel Certainty="75">Warning</MessageLevel>
   <File Name="dataflowrules.dll" Version="15.0.0.0" />
  </Rule>
  <Rule TypeName="RethrowToPreserveStackDetails" Category="Microsoft.Usage" CheckId="CA2200">
   <Name>Reiniciar para mantener los detalles de la pila</Name>
   <Description>Utilice la instrucción de reinicio IL para mantener los detalles de la pila original cuando vaya a volver a provocar la excepción detectada.</Description>
   <Resolution Name="Default">{0} vuelve a producir una excepción detectada y la especifica explícitamente como un argumento. Utilice 'throw' sin un argumento, para mantener la ubicación de la pila donde se provocó inicialmente la excepción.</Resolution>
   <Owner />
   <Url>http://msdn.microsoft.com/library/ms182363.aspx</Url>
   <Email>[none]</Email>
   <MessageLevel Certainty="95">Error</MessageLevel>
   <File Name="usagerules.dll" Version="15.0.0.0" />
  </Rule>
 </Rules>
 <Localized>
  <String Key="Category">Categoría</String>
  <String Key="Certainty">Certeza</String>
  <String Key="CollapseAll">Contraer todo</String>
  <String Key="CheckId">Comprobar id.</String>
  <String Key="Error">Error</String>
  <String Key="Errors">errores</String>
  <String Key="ExpandAll">Expandir todo</String>
  <String Key="Help">Ayuda</String>
  <String Key="Line">Línea</String>
  <String Key="Messages">mensajes</String>
  <String Key="LocationNotStoredInPdb">[Ubicación no almacenada en Pdb]</String>
  <String Key="Project">Proyecto</String>
  <String Key="Resolution">Resolución</String>
  <String Key="Rule">Regla</String>
  <String Key="RuleFile">Archivo de regla</String>
  <String Key="RuleDescription">Descripción de la regla</String>
  <String Key="Source">Origen</String>
  <String Key="Status">Estado</String>
  <String Key="Target">Círculos concéntricos</String>
  <String Key="Warning">Advertencia</String>
  <String Key="Warnings">advertencias</String>
  <String Key="ReportTitle">Informe de análisis del código</String>
 </Localized>
</FxCopReport>
